@startuml Agregar producto al carrito
Title "Cancelar Orden"
actor Navegador as nav
boundary "ordenes.ejs" as UI
boundary "orden.routes.js" as ruta
control "orden.controller.js" as ctrl
entity "orden.model.js" as model
entity "configuracion.model.js" as model3
database "Postgres (Supabase)" as DB

activate nav
nav -> ruta: POST /orden/cancel (id_orden)
deactivate nav
activate ruta
ruta -> ctrl: cancelarOrden(id_orden)
deactivate ruta
activate ctrl
ctrl ->> model: ObtenerOrdenPorId(id_orden)
activate model
model ->> DB: .from('orden') .select('*') .eq('id_orden', id_orden)
activate DB
DB -->> model: Orden
deactivate DB
model -->> ctrl: Orden
deactivate model
ctrl ->> model3: ObtenerConfiguracionActiva
activate model3
model3 ->> DB: .from('configuracion') .select('*') .eq('activo', True) 
activate DB
DB -->> model3: Configuracion
deactivate DB
model3 -->> ctrl: Configuracion
deactivate model3

ctrl -> ctrl: esCancelable = validarTiempo(orden, config)

alt esCancelable == true
    ctrl ->> model: cancelarOrden(id_orden)
    activate model
    model ->> DB: update estado = "Cancelada"
    activate DB
    DB -->> model: Se cancelo la orden
    deactivate DB
    model -->> ctrl: Se cancelo la orden
    deactivate model
else esCancelable == false
    ctrl -> ctrl :req.session.error = "No se puede cancelar"
end
ctrl -->> ruta :response.redirect('/orden')
deactivate ctrl
activate ruta

ruta -> ctrl: getMisOrdenes()
deactivate ruta
activate ctrl
ctrl ->> model: ObtenerOrdenesPorUsuario(id_usuario)
activate model
model ->> DB: .from('orden') .select("*") .eq('id_usuario', id_usuario)
activate DB
DB -->> model: ordenes
deactivate DB
model -->> ctrl: ordenes
deactivate model


ctrl --> UI: response.render("cliente/ordenes", {ordenes: ordenes, error: request.session.error})
deactivate ctrl
activate UI
UI --> nav: Vista
deactivate UI
activate nav

@enduml