@startuml Modificar Producto del Carrito
Title "Modificar Producto del Carrito"

actor Navegador as nav
control "carrito.js" as JS
boundary "carrito.routes.js" as ruta
boundary "carrito.ejs" as UI
control "carrito.controller.js" as ctrl
entity "detalle_orden.model.js" as model
database "Postgres (Supabase)" as DB

activate nav
nav -> ruta: POST /carrito/items/id_producto 
deactivate nav

activate ruta
ruta -> ctrl:  actualizarItem(request, response)
deactivate ruta
activate ctrl

alt request.body.cantidad_ingresada = 0
    ctrl ->> model: eliminarProducto(id_producto)
    activate model
    model ->> DB: .from('detalle_orden') .delete() .eq('id_producto', id_producto)
    activate DB
    DB -->> model
    deactivate DB
    model -->> ctrl
    deactivate model
    
else request.body.cantidad != 0
    ctrl ->> model: modificarCantidad(id_producto, cantidad_ingresada)
    activate model
    model ->> DB: UPDATE cantidad = cantidad_ingresada
    activate DB
    DB -->> model
    deactivate DB
    model -->> ctrl

    deactivate model
end

ctrl --> ruta: JSON (resultado)
deactivate ctrl
activate ruta

ruta --> JS: JSON (resultado)
deactivate ruta

activate JS
alt data.eliminado = true
    
    JS -> UI: mostrarEliminado(nombre, idProducto)\nrow.remove()
    activate UI
    deactivate UI
else data.eliminado = false
    JS -> UI: qtySpan.textContent = data.nuevaCantidad\nprice.textContent = precio × nuevaCantidad
    activate UI
    deactivate UI
end
JS -> UI: actualizarSubtotal()
deactivate JS


activate UI
UI --> nav: Vista actualizada
deactivate UI
activate nav


@enduml